# Generated by Django 5.2.8 on 2025-11-12 05:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Exemple : 6ème A', max_length=50, unique=True)),
                ('niveau', models.CharField(blank=True, help_text='Cycle ou niveau associé (ex: Collège, Lycée).', max_length=50)),
                ('responsable', models.CharField(blank=True, help_text='Nom du professeur principal ou personne référente.', max_length=100)),
            ],
            options={
                'verbose_name': 'classe',
                'verbose_name_plural': 'classes',
                'ordering': ('nom',),
            },
        ),
        migrations.CreateModel(
            name='DepenseCantine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=120)),
                ('categorie', models.CharField(choices=[('ingredients', 'Ingrédients'), ('gaz', 'Gaz / énergie'), ('main_oeuvre', "Main d'œuvre"), ('logistique', 'Logistique'), ('autre', 'Autre')], default='ingredients', max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'dépense cantine',
                'verbose_name_plural': 'dépenses cantine',
                'ordering': ('-date', 'libelle'),
            },
        ),
        migrations.CreateModel(
            name='MenuJournalier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('entree', models.CharField(blank=True, max_length=150)),
                ('plat_principal', models.CharField(max_length=150)),
                ('accompagnement', models.CharField(blank=True, max_length=150)),
                ('dessert', models.CharField(blank=True, max_length=150)),
                ('boisson', models.CharField(blank=True, max_length=150)),
                ('commentaires', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'menu journalier',
                'verbose_name_plural': 'menus journaliers',
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(help_text='Identifiant unique interne ou scolaire.', max_length=30, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_inscription', models.DateField(default=django.utils.timezone.now)),
                ('actif', models.BooleanField(default=True, help_text="Indique si l'élève est actuellement inscrit au service de cantine.")),
                ('contact_parent', models.CharField(blank=True, help_text='Téléphone du parent ou tuteur.', max_length=50)),
                ('email_parent', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eleves', to='cantine.classe')),
            ],
            options={
                'verbose_name': 'élève',
                'verbose_name_plural': 'élèves',
                'ordering': ('nom', 'prenom'),
            },
        ),
        migrations.CreateModel(
            name='AbonnementCantine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('en_attente', 'En attente'), ('suspendu', 'Suspendu'), ('termine', 'Terminé')], default='actif', max_length=15)),
                ('date_debut', models.DateField(default=django.utils.timezone.now)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('solde', models.DecimalField(decimal_places=2, default=0, help_text='Solde positif = crédit disponible, négatif = montant dû.', max_digits=9)),
                ('montant_mensuel', models.DecimalField(decimal_places=2, default=0, help_text='Montant facturé mensuellement pour ce forfait.', max_digits=9)),
                ('eleve', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='abonnement', to='cantine.eleve')),
            ],
            options={
                'verbose_name': 'abonnement cantine',
                'verbose_name_plural': 'abonnements cantine',
            },
        ),
        migrations.CreateModel(
            name='PresenceRepas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('repas', models.CharField(choices=[('dejeuner', 'Déjeuner'), ('diner', 'Dîner')], default='dejeuner', max_length=20)),
                ('present', models.BooleanField(default=True)),
                ('heure_pointage', models.TimeField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='cantine.eleve')),
            ],
            options={
                'verbose_name': 'présence repas',
                'verbose_name_plural': 'présences repas',
                'ordering': ('-date', 'eleve__nom'),
                'constraints': [models.UniqueConstraint(fields=('eleve', 'date', 'repas'), name='unique_presence_par_repas')],
            },
        ),
    ]
