# Generated by Django 5.2.8 on 2025-11-12 06:01

import cantine.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cantine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='menujournalier',
            name='photo',
            field=models.ImageField(blank=True, help_text='Photo illustrative du menu du jour.', upload_to=cantine.models.upload_menu_journalier),
        ),
        migrations.CreateModel(
            name='MenuMensuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('mois', models.IntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')])),
                ('annee', models.PositiveIntegerField(default=2025)),
                ('description', models.TextField(blank=True)),
                ('couverture', models.ImageField(blank=True, help_text='Image de couverture pour présenter le menu du mois.', upload_to=cantine.models.upload_menu_mensuel)),
                ('document', models.FileField(blank=True, help_text='Fichier PDF ou document détaillant le menu.', upload_to=cantine.models.upload_menu_mensuel)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'menu mensuel',
                'verbose_name_plural': 'menus mensuels',
                'ordering': ('-annee', '-mois'),
                'unique_together': {('mois', 'annee')},
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administration'), ('prestataire', 'Prestataire')], default='admin', max_length=20)),
                ('avatar', models.ImageField(blank=True, help_text='Photo de profil (affichage circulaire).', null=True, upload_to=cantine.models.upload_avatar)),
                ('contact', models.CharField(blank=True, max_length=50)),
                ('poste', models.CharField(blank=True, max_length=80)),
                ('bio', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profil utilisateur',
                'verbose_name_plural': 'profils utilisateurs',
            },
        ),
    ]
