# Generated by Django 5.2.8 on 2025-11-12 07:43

import cantine.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cantine', '0002_menujournalier_photo_menumensuel_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=cantine.models.upload_eleve_photo),
        ),
        migrations.AddField(
            model_name='presencerepas',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presences', to='cantine.menujournalier'),
        ),
    ]
